spring:
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:file:~/workspace/vdf_spring/h2;DB_CLOSE_ON_EXIT=FALSE
    jpa:
        hibernate:
          ddl-auto: update

security:
  oauth2:
    client:
      clientId: 214006909435830
      clientSecret: e84e502361d0742ebdc693133dafc2ee
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
